import Image from "next/image";

export const metadata = {
  title: {
    absolute: "Victor Chigbo | Speaker Bio",
  },
  description:
    "Tech Extrovert, Enthusiast and Polymath || Software Engineer || Front-End Web Developer",
  // description: "Generated by create next app",
  openGraph: {
    title: "Victor Chigbo",
    description:
      "Tech Extrovert, Enthusiast and Polymath || Software Engineer || Front-End Web Developer",
    type: "website",
  },
  author: "Victor Chigbo",
  keywords: [
    "Victor",
    "Chigbo",
    "chivicks_hazard",
    "Chivicks",
    "Hazard",
    "Victor Chigbo",
    "Chivicks Hazard",
    "speaker bio",
    "speaker",
    "bio",
    "about",
  ],
};

const SpeakerBioPage = () => {
  return (
    <main id="skillset">
      <div className="mt-32">
        <div className="mt-5 pt-3 max-sm:mx-3">
          <h1 className="text-4xl md:text-6xl text-center mb-10 text-aliceblue">
            Speaker Bio
          </h1>

          <Image
            src="/images/profile_pic_1.jpg"
            alt="Victor Chigbo"
            width={0}
            height={0}
            sizes="100vw"
            className="mx-auto rounded-sm w-full md:w-2/3 lg:w-1/3"
          />

          <p className="text-xl md:text-2xl md:w-3/4 md:mx-auto mt-30 mb-10">
            Victor Chigbo (aka Chivicks Hazard) is a software engineer and
            frontend developer passionate about crafting responsive,
            user-focused web interfaces that are intuitive, accessible, and
            delightful to use. With experience building scalable frontends using
            modern technologies like JavaScript, TypeScript, React, Next.js, and
            Tailwind CSS, Victor prioritizes performance, accessibility, and
            seamless user experience in every project he undertakes.
            <br />
            <br />
            Victor is continuously expanding his expertise in system design,
            software architecture, analytical problem-solving, data structures &
            algorithms (DSA), testing, documentation, and agile development
            practices — driven by a deep commitment to personal growth and
            continuous learning. His approach reflects not just technical skill,
            but a growth mindset that fuels his journey from frontend focus
            toward fullstack capability. <br />
            <br />
            More than a coder, Victor is a tech extrovert, enthusiast, and
            polymath. He loves discussing tech trends, exploring emerging
            technologies, and picking up new skills like a gem collector.
            Whether attending, volunteering, or speaking at events — both
            virtually and in person — his presence is defined by curiosity,
            energy, and connection with the tech community.
            <br />
            <br />
            Victor’s engagement in tech communities has broadened his
            professional network and strengthened his skills in community
            management, leadership, and technology communication. He believes
            that building relationships and sharing knowledge are fundamental to
            personal and collective growth. <br />
            <br />
            Victor is open to collaborations where he can help transform ideas
            into reality on the web, architect intuitive user experiences, and
            contribute meaningful insights across systems and technologies. He
            continues to learn, build, and connect — striving to elevate both
            his craft and the communities around him.
          </p>
        </div>
      </div>
    </main>
  );
};

export default SpeakerBioPage;
