import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Josefin_Sans } from "next/font/google";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import "./globals.css";

// const JosefinSans = localFont({
//   variable: "--font-josefin-sans",
//   src: "../../public/fonts/JosefinSans-VariableFont_wght.ttf",
//   subsets: ["latin"],
// });

const JosefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "Victor Chigbo | %s",
    default: "Victor Chigbo",
  },
  description:
    "Tech Extrovert, Enthusiast and Polymath || Software Engineer || Front-End Web Developer",
  // description: "Generated by create next app",
  openGraph: {
    title: "Victor Chigbo",
    description:
      "Tech Extrovert, Enthusiast and Polymath || Software Engineer || Front-End Web Developer",
    type: "website",
  },
  author: "Victor Chigbo",
  keywords: [
    "Victor",
    "Chigbo",
    "chivicks_hazard",
    "Chivicks",
    "Hazard",
    "Victor Chigbo",
    "Chivicks Hazard",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={JosefinSans.className}>
      <body
      // className={}
      >
        <Navbar />
        {children}
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
